[package]
name = "rtl8710-sdk"
version = "0.1.0"
authors = ["David Goodlad <david@goodlad.net>"]
edition = "2018"

[dependencies]
cty = "0.2"

[build-dependencies]
cc = { version = "1.0", features = ["parallel"] }
bindgen = "0.49.0"
llvm-tools = "0.1.1"
